
-- ZARO STORE DATABASE
-- Run this whole file in Supabase -> SQL Editor.
-- Then create your admin account from Supabase -> Authentication -> Users.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  ar text,
  cat text not null default 'T-Shirts',
  price numeric(10,2) not null default 0,
  image text,
  sizes jsonb not null default '[]'::jsonb,
  stock integer not null default 0,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone text not null,
  address text not null,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  delivery numeric(10,2) not null default 10,
  total numeric(10,2) not null default 0,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key default 1,
  brand_name text not null default 'ZARO',
  whatsapp text not null default '201000000000',
  delivery_fee numeric(10,2) not null default 10,
  announcement text not null default 'NEW DROP',
  hero_title text not null default 'STYLE BUILT DIFFERENT.',
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1)
on conflict (id) do nothing;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
on public.orders for insert
to anon, authenticated
with check (
  length(trim(customer_name)) between 2 and 100
  and length(trim(phone)) between 5 and 30
  and length(trim(address)) between 5 and 300
  and total >= 0
);


drop policy if exists "public can view active products" on public.products;
create policy "public can view active products"
on public.products for select
to anon, authenticated
using (active = true);

drop policy if exists "authenticated admins can manage products" on public.products;
create policy "authenticated admins can manage products"
on public.products for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated admins can view orders" on public.orders;
create policy "authenticated admins can view orders"
on public.orders for select
to authenticated
using (true);

drop policy if exists "authenticated admins can update orders" on public.orders;
create policy "authenticated admins can update orders"
on public.orders for update
to authenticated
using (true)
with check (true);

drop policy if exists "public can read settings" on public.site_settings;
create policy "public can read settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "authenticated admins can manage settings" on public.site_settings;
create policy "authenticated admins can manage settings"
on public.site_settings for all
to authenticated
using (true)
with check (true);

-- Storage bucket for product photos.
insert into storage.buckets (id, name, public)
values ('zaro-products', 'zaro-products', true)
on conflict (id) do update set public = true;

drop policy if exists "public can view zaro product images" on storage.objects;
create policy "public can view zaro product images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'zaro-products');

drop policy if exists "authenticated can upload zaro product images" on storage.objects;
create policy "authenticated can upload zaro product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'zaro-products');

drop policy if exists "authenticated can update zaro product images" on storage.objects;
create policy "authenticated can update zaro product images"
on storage.objects for update
to authenticated
using (bucket_id = 'zaro-products')
with check (bucket_id = 'zaro-products');

drop policy if exists "authenticated can delete zaro product images" on storage.objects;
create policy "authenticated can delete zaro product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'zaro-products');

-- Optional: make sure your first admin user can access everything.
-- Create the user first in Authentication -> Users.
